#!/bin/bash
# Skript kusib kasutajalt nime ja tervitab teda
echo –n “Sisesta oma ees- ja perenimi: ”
read eesnimi perenimi
# Valjastame tervituse ja kasutaja nime
echo “Sinu eesnimi on $eesnimi ja perenimi on $perenimi”
# Skripti lopp
